import type { Recipe, InventoryItem, ProductionLog, Supplier, PurchaseOrder, Product, Sale } from "./types"

export const MOCK_RECIPES: Recipe[] = [
  {
    id: "1",
    name: "Chocolate Donuts",
    yield: 24,
    yieldUnit: "pieces",
    ingredients: [
      { id: "i1", name: "All-Purpose Flour", quantity: 500, unit: "g" },
      { id: "i2", name: "White Sugar", quantity: 100, unit: "g" },
      { id: "i3", name: "Cocoa Powder", quantity: 50, unit: "g" },
      { id: "i4", name: "Eggs", quantity: 3, unit: "pieces" },
      { id: "i5", name: "Milk", quantity: 250, unit: "ml" },
      { id: "i6", name: "Butter", quantity: 100, unit: "g" },
      { id: "i7", name: "Baking Powder", quantity: 10, unit: "g" },
      { id: "i8", name: "Salt", quantity: 5, unit: "g" },
    ],
    instructions:
      "1. Mix dry ingredients (flour, sugar, cocoa powder, baking powder, salt) in a large bowl.\n2. In another bowl, whisk eggs, milk, and melted butter.\n3. Combine wet and dry ingredients until just mixed.\n4. Pipe batter into greased donut pans.\n5. Bake at 180°C for 12-15 minutes.\n6. Cool and glaze as desired.",
    category: 'pastries',
    tags: [],
    createdAt: new Date("2025-01-01"),
    updatedAt: new Date("2025-01-01"),
  },
  {
    id: "2",
    name: "Ensaymada",
    yield: 12,
    yieldUnit: "pieces",
    ingredients: [
      { id: "i9", name: "Bread Flour", quantity: 400, unit: "g" },
      { id: "i10", name: "White Sugar", quantity: 80, unit: "g" },
      { id: "i11", name: "Eggs", quantity: 2, unit: "pieces" },
      { id: "i12", name: "Milk", quantity: 150, unit: "ml" },
      { id: "i13", name: "Butter", quantity: 150, unit: "g" },
      { id: "i14", name: "Yeast", quantity: 7, unit: "g" },
      { id: "i15", name: "Salt", quantity: 5, unit: "g" },
      { id: "i16", name: "Cheese (grated)", quantity: 100, unit: "g" },
    ],
    instructions:
      "1. Activate yeast in warm milk with a pinch of sugar.\n2. Mix flour, sugar, and salt in a bowl.\n3. Add eggs, yeast mixture, and knead until smooth.\n4. Gradually add butter and knead for 10 minutes.\n5. Let dough rise for 1 hour.\n6. Roll out, spread butter, roll into logs, and coil.\n7. Let rise again for 30 minutes.\n8. Bake at 175°C for 15-18 minutes.\n9. Brush with butter and top with sugar and cheese.",
    category: 'bread',
    tags: [],
    createdAt: new Date("2025-01-02"),
    updatedAt: new Date("2025-01-02"),
  },
  {
    id: "3",
    name: "Pandesal",
    yield: 50,
    yieldUnit: "pieces",
    ingredients: [
      { id: "i17", name: "Bread Flour", quantity: 1000, unit: "g" },
      { id: "i18", name: "White Sugar", quantity: 100, unit: "g" },
      { id: "i19", name: "Yeast", quantity: 15, unit: "g" },
      { id: "i20", name: "Salt", quantity: 10, unit: "g" },
      { id: "i21", name: "Water", quantity: 500, unit: "ml" },
      { id: "i22", name: "Vegetable Oil", quantity: 50, unit: "ml" },
      { id: "i23", name: "Breadcrumbs", quantity: 100, unit: "g" },
    ],
    instructions:
      "1. Dissolve yeast in warm water with sugar.\n2. Mix flour and salt in a large bowl.\n3. Add yeast mixture and oil, knead for 10 minutes.\n4. Let dough rise for 1 hour until doubled.\n5. Punch down and divide into small portions.\n6. Roll in breadcrumbs and shape into ovals.\n7. Let rise for 30 minutes.\n8. Bake at 180°C for 15-20 minutes until golden.",
    category: 'bread',
    tags: [],
    createdAt: new Date("2025-01-03"),
    updatedAt: new Date("2025-01-03"),
  },
]

export const MOCK_INVENTORY: InventoryItem[] = [
  // Raw Materials
  {
    id: "inv1",
    name: "All-Purpose Flour",
    type: "raw",
    quantity: 15000,
    unit: "g",
    minStock: 5000,
    expirationDate: new Date("2025-01-12"),
    deliveryDate: new Date("2024-12-15"),
    lastUpdated: new Date("2025-01-08"),
  },
  {
    id: "inv2",
    name: "White Sugar",
    type: "raw",
    quantity: 5000,
    unit: "g",
    minStock: 8000,
    expirationDate: new Date("2025-06-30"),
    deliveryDate: new Date("2024-12-20"),
    lastUpdated: new Date("2025-01-08"),
  },
  {
    id: "inv3",
    name: "Bread Flour",
    type: "raw",
    quantity: 12000,
    unit: "g",
    minStock: 5000,
    expirationDate: new Date("2025-02-15"),
    deliveryDate: new Date("2025-01-05"),
    lastUpdated: new Date("2025-01-08"),
  },
  {
    id: "inv4",
    name: "Butter",
    type: "raw",
    quantity: 3000,
    unit: "g",
    minStock: 2000,
    expirationDate: new Date("2025-01-20"),
    deliveryDate: new Date("2025-01-02"),
    lastUpdated: new Date("2025-01-08"),
  },
  {
    id: "inv5",
    name: "Eggs",
    type: "raw",
    quantity: 120,
    unit: "pieces",
    minStock: 60,
    expirationDate: new Date("2025-01-15"),
    deliveryDate: new Date("2025-01-06"),
    lastUpdated: new Date("2025-01-08"),
  },
  {
    id: "inv6",
    name: "Milk",
    type: "raw",
    quantity: 8000,
    unit: "ml",
    minStock: 5000,
    expirationDate: new Date("2025-01-14"),
    deliveryDate: new Date("2025-01-07"),
    lastUpdated: new Date("2025-01-08"),
  },
  // Finished Goods
  {
    id: "inv7",
    name: "Chocolate Donuts",
    type: "finished",
    quantity: 8,
    unit: "pieces",
    minStock: 12,
    lastUpdated: new Date("2025-01-10"),
  },
  {
    id: "inv8",
    name: "Ensaymada",
    type: "finished",
    quantity: 24,
    unit: "pieces",
    minStock: 12,
    lastUpdated: new Date("2025-01-10"),
  },
  {
    id: "inv9",
    name: "Pandesal",
    type: "finished",
    quantity: 85,
    unit: "pieces",
    minStock: 50,
    lastUpdated: new Date("2025-01-10"),
  },
  {
    id: "inv10",
    name: "Ube Cake Slice",
    type: "finished",
    quantity: 16,
    unit: "pieces",
    minStock: 10,
    lastUpdated: new Date("2025-01-10"),
  },
]

export const MOCK_PRODUCTION_LOGS: ProductionLog[] = [
  {
    id: "prod1",
    recipeId: "1",
    recipeName: "Chocolate Donuts",
    quantityProduced: 24,
    productionDate: new Date("2025-01-10T08:30:00"),
    bakerName: "Juan Cruz",
  },
  {
    id: "prod2",
    recipeId: "2",
    recipeName: "Ensaymada",
    quantityProduced: 12,
    productionDate: new Date("2025-01-10T09:15:00"),
    bakerName: "Juan Cruz",
  },
  {
    id: "prod3",
    recipeId: "3",
    recipeName: "Pandesal",
    quantityProduced: 50,
    productionDate: new Date("2025-01-10T06:00:00"),
    bakerName: "Juan Cruz",
  },
]

export const MOCK_SUPPLIERS: Supplier[] = [
  {
    id: "sup1",
    name: "Manila Flour Mills",
    contactPerson: "Roberto Santos",
    email: "roberto@manilaflour.com",
    phone: "+63 2 1234 5678",
    address: "123 Industrial Ave, Manila",
    products: ["All-Purpose Flour", "Bread Flour", "Cake Flour"],
    createdAt: new Date("2024-06-01"),
  },
  {
    id: "sup2",
    name: "Sweet Supplies Co.",
    contactPerson: "Maria Garcia",
    email: "maria@sweetsupplies.ph",
    phone: "+63 2 2345 6789",
    address: "456 Commerce St, Quezon City",
    products: ["White Sugar", "Brown Sugar", "Cocoa Powder", "Vanilla Extract"],
    createdAt: new Date("2024-06-15"),
  },
  {
    id: "sup3",
    name: "Dairy Fresh",
    contactPerson: "Carlos Reyes",
    email: "carlos@dairyfresh.ph",
    phone: "+63 2 3456 7890",
    address: "789 Dairy Road, Makati",
    products: ["Milk", "Butter", "Cream", "Cheese"],
    createdAt: new Date("2024-07-01"),
  },
  {
    id: "sup4",
    name: "Farm Fresh Eggs",
    contactPerson: "Ana Lopez",
    email: "ana@farmfresheggs.ph",
    phone: "+63 2 4567 8901",
    address: "321 Farm Lane, Laguna",
    products: ["Eggs", "Egg Whites", "Egg Yolks"],
    createdAt: new Date("2024-07-15"),
  },
]

export const MOCK_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: "po1",
    orderNumber: "PO-2025-001",
    supplierId: "sup1",
    supplierName: "Manila Flour Mills",
    items: [
      {
        id: "poi1",
        itemName: "All-Purpose Flour",
        quantity: 50,
        unit: "kg",
        unitPrice: 45,
        totalPrice: 2250,
      },
      {
        id: "poi2",
        itemName: "Bread Flour",
        quantity: 30,
        unit: "kg",
        unitPrice: 50,
        totalPrice: 1500,
      },
    ],
    totalAmount: 3750,
    status: "pending",
    orderDate: new Date("2025-01-08"),
    expectedDeliveryDate: new Date("2025-01-12"),
    notes: "Urgent order for weekend production",
  },
  {
    id: "po2",
    orderNumber: "PO-2025-002",
    supplierId: "sup2",
    supplierName: "Sweet Supplies Co.",
    items: [
      {
        id: "poi3",
        itemName: "White Sugar",
        quantity: 25,
        unit: "kg",
        unitPrice: 55,
        totalPrice: 1375,
      },
      {
        id: "poi4",
        itemName: "Cocoa Powder",
        quantity: 5,
        unit: "kg",
        unitPrice: 280,
        totalPrice: 1400,
      },
    ],
    totalAmount: 2775,
    status: "received",
    orderDate: new Date("2025-01-07"),
    expectedDeliveryDate: new Date("2025-01-10"),
    actualDeliveryDate: new Date("2025-01-09"),
  },
  {
    id: "po3",
    orderNumber: "PO-2025-003",
    supplierId: "sup3",
    supplierName: "Dairy Fresh",
    items: [
      {
        id: "poi5",
        itemName: "Butter",
        quantity: 10,
        unit: "kg",
        unitPrice: 320,
        totalPrice: 3200,
      },
      {
        id: "poi6",
        itemName: "Milk",
        quantity: 20,
        unit: "L",
        unitPrice: 85,
        totalPrice: 1700,
      },
    ],
    totalAmount: 4900,
    status: "pending",
    orderDate: new Date("2025-01-06"),
    expectedDeliveryDate: new Date("2025-01-11"),
  },
  {
    id: "po4",
    orderNumber: "PO-2024-125",
    supplierId: "sup4",
    supplierName: "Farm Fresh Eggs",
    items: [
      {
        id: "poi7",
        itemName: "Eggs",
        quantity: 300,
        unit: "pieces",
        unitPrice: 8,
        totalPrice: 2400,
      },
    ],
    totalAmount: 2400,
    status: "received",
    orderDate: new Date("2024-12-28"),
    expectedDeliveryDate: new Date("2025-01-02"),
    actualDeliveryDate: new Date("2025-01-02"),
  },
]

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "prod1",
    name: "Chocolate Donuts",
    price: 50,
    category: "Donuts",
    inStock: 8,
  },
  {
    id: "prod2",
    name: "Ensaymada",
    price: 50,
    category: "Pastries",
    inStock: 24,
  },
  {
    id: "prod3",
    name: "Pandesal (Pack of 10)",
    price: 40,
    category: "Bread",
    inStock: 85,
  },
  {
    id: "prod4",
    name: "Ube Cake Slice",
    price: 80,
    category: "Cakes",
    inStock: 16,
  },
  {
    id: "prod5",
    name: "Cheese Bread",
    price: 40,
    category: "Bread",
    inStock: 32,
  },
  {
    id: "prod6",
    name: "Glazed Donuts",
    price: 45,
    category: "Donuts",
    inStock: 18,
  },
  {
    id: "prod7",
    name: "Spanish Bread",
    price: 35,
    category: "Bread",
    inStock: 28,
  },
  {
    id: "prod8",
    name: "Chocolate Cake Slice",
    price: 85,
    category: "Cakes",
    inStock: 12,
  },
  {
    id: "prod9",
    name: "Cinnamon Roll",
    price: 55,
    category: "Pastries",
    inStock: 15,
  },
  {
    id: "prod10",
    name: "Banana Muffin",
    price: 45,
    category: "Muffins",
    inStock: 20,
  },
]

export const MOCK_SALES: Sale[] = [
  {
    id: "sale1",
    orderNumber: "ORD-2025-001",
    items: [
      { product: MOCK_PRODUCTS[0], quantity: 3 },
      { product: MOCK_PRODUCTS[2], quantity: 2 },
    ],
    subtotal: 230,
    tax: 0,
    total: 230,
    paymentMethod: "cash",
    amountPaid: 250,
    change: 20,
    cashierName: "Ana Reyes",
    saleDate: new Date("2025-01-10T09:15:00"),
  },
  {
    id: "sale2",
    orderNumber: "ORD-2025-002",
    items: [
      { product: MOCK_PRODUCTS[1], quantity: 5 },
      { product: MOCK_PRODUCTS[3], quantity: 2 },
    ],
    subtotal: 410,
    tax: 0,
    total: 410,
    paymentMethod: "gcash",
    amountPaid: 410,
    change: 0,
    cashierName: "Ana Reyes",
    saleDate: new Date("2025-01-10T10:30:00"),
  },
]

export const mockRecipes = MOCK_RECIPES
export const mockProductionLogs = MOCK_PRODUCTION_LOGS
